# Generated by Django 6.0.6 on 2026-06-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event/thumbnail')),
                ('category', models.CharField(choices=[('CONFERENCE', 'Conference'), ('PARTY', 'Party'), ('WEDDING', 'Wedding'), ('SEMINAR', 'Seminar'), ('OTHER', 'Other')], default='CONFERENCE', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('IN-PERSON', 'In-Person'), ('BOTH', 'Both')], default='ONLINE', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(blank=True, choices=[('GHC', 'Ghc'), ('RAND', 'Rand'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound')], default='GHC', max_length=10, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('ENDED', 'Ended')], default='UPCOMING', max_length=10)),
                ('registration_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EventSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event/speakers')),
            ],
        ),
        migrations.CreateModel(
            name='EventTags',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('registered', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ManyToManyField(to='event.eventagenda')),
                ('gallery', models.ManyToManyField(to='event.eventgallery')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventlist')),
                ('organizers', models.ManyToManyField(to='event.eventorganizer')),
                ('speakers', models.ManyToManyField(to='event.eventspeakers')),
                ('tags', models.ManyToManyField(to='event.eventtags')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventvenue')),
            ],
        ),
    ]
