# Generated by Django 6.0.6 on 2026-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='event_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
