# Generated by Django 6.0.6 on 2026-06-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventlist_event_id_alter_eventlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='eventdetail',
            name='venue',
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.eventdetail'),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='event.eventdetail'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='event.eventdetail'),
        ),
        migrations.AddField(
            model_name='eventspeakers',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='event.eventdetail'),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='event.eventdetail'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='event.eventlist'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='event.eventtags'),
        ),
    ]
