# Generated by Django 6.0.6 on 2026-06-26 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_eventdetail_agenda_remove_eventdetail_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetail',
            name='tags',
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.eventdetail'),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='event.eventdetail'),
        ),
        migrations.AlterField(
            model_name='eventspeakers',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='event.eventdetail'),
        ),
        migrations.DeleteModel(
            name='EventTags',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
